module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  Lectures:
    filename: src/Lectures.hs
  Application:
    filename: src/Application.hs
  Eval:
    filename: src/Eval.hs
  Site:
    filename: src/Site.hs
  Main(src/Main.hs):
    filename: src/Main.hs
version: 1
ghc-args: []
