sudo: false
language: generic
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- cd _site
- git checkout gh-pages
- git pull origin gh-pages
- cd ..
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc build
script:
- stack exec site rebuild
machine:
  timezone: Europe/Berlin
after_success:
- cd _site
- git config --global user.email deploy@travis-ci.org
- git config --global user.name Deployment Bot
- git checkout gh-pages
- git add docs
- git commit -m "Update site (`date '+%F %T %Z'`)"
- git push "https://${GH_TOKEN}@github.com/obcode/ob.cs.hm.edu.git" gh-pages
env:
  global:
    secure: dm8sqQ8onvZfKCIlRioB2adlu48NpaLdUJ2cOz+zwiMRHTHvR+mvmdv/IqDxJcDfKUNcZ74Thy+naRYkcpPZVCeEMG+QYntOyKjBx7ahkcWh5bFtuUaTvY6HYWUweLkeDS+q0FDXfdqRXdVQsi9WygUeIcLcwdG94k4jTPD6z8E=
